### ISSUE TITLE
Remove `compress` option

### ISSUE THREAD

**Issue by sindresorhus** [addyosmani/gulp-uncss-task#1]
See https://github.com/sindresorhus/gulp-styl/issues/2 and https://github.com/sindresorhus/gulp-styl/commit/db68d79e3abed99d214c53b940bd1a3fbc035861#diff-0730bb7c2e8f9ea2438b52e419dd86c9R33

**Comment by tomByrer** [comment]
I'm curious how the output is different from [clean-css](https://github.com/jonathanepollack/gulp-minify-css) & UnCSS-then-[CSSO](https://github.com/ben-eb/gulp-csso)?  Or from [another UnCSS](https://github.com/ben-eb/gulp-uncss/blob/master/index.js)? ;)
But did you notice it seems UnCSS [uses CSSO](https://github.com/giakki/uncss/blob/master/lib/uncss.js)?

-1; one less plugin to install, when both use same code-base.

**Comment by sindresorhus** [comment]
@tomByrer CSSO is the best CSS compressor. It's about separating concerns. Gulp is not grunt.

**Comment by tomByrer** [comment]
I understand Gulp-tasks are to handle only one thing.  Some people, including myself, don't want to re-install the same package twice.

Or maybe fork UnCSS to take out those 4 of lines to not use CSSO.

Edit: One can look at 'make smallest CSS' as "do one thing" (even though behind the scenes it really is 'reduce then compress').  OTOH, removing compression will make it different than the other gulp-uncss.

**Comment by sindresorhus** [comment]
You don't install anything twice. Npm does. Sounds like grunt would be a better fit for you.

**Comment by tomByrer** [comment]
> You don't install anything twice. Npm does.

Well, yea, same difference :P
Sorry, I just don't see the point of wrapping the same lib twice, so I guess we agree we both disagree :)

I DO agree with the concept of separating concerns & making code simpler; I don't really see the need of UnCSS to include CSSO, so please [add your feedback there](https://github.com/giakki/uncss/issues/17).

**Comment by sindresorhus** [comment]
What I'm trying to make you see is that node is not the web. Having multiple instances of one dep is totally normal. In some of my modules I have different deps of Lodash in multiple levels of the dep three, since some of my deps and dep children depend on it. This matters so little and something you shouldn't even think about. It does not matter a bit. You can also use `npm dedupe` if it really bothers you and npm will make it one dep.

Thanks for opening that issue. I agree. UnCSS shouldn't bundle it.
